[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio", "node-telegram-bot-api", "@supabase/supabase-js"]
  included_files = ["**/*.json"]

[functions.hello]
  timeout = 30

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-functions-scheduled-functions"
  [plugins.inputs]
    telegram_bot = "*/10 * * * *"
    telegram_monitor = "0 * * * *"

[[redirects]]
  from = "/api/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
